### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by PeterKottas** [DarkLiKally/I18Next.Net#10]
Hi, sorry for the weird issue. I am trying to decide on i18n solution for a rather big project we're working on. We are already using i18next on the frontend which would make this perfect in terms of compatibility of tools and the build process. 

I, however, see that this lib is not widely adopted, and in order to save precious time, I was curious if you could help me understand the state of its development. Is this actively developed/maintained? Are there any issues that you currently are aware of that need fixing and/or is it ready for production? Did you do any performance testing comparing it to the more traditional dot net i18n frameworks? 

Thank you very much for any kind of feedback you could provide here.

**Comment by DarkLiKally** [comment]
Hello @PeterKottas,

we're using the package in production internally and at some projects of our customers. We had no problems so far in our solutions.

I'm not aware whether there are missing features that are required by other users and we have no known issues so far in general.
If you have suggestions or detect some issues please report them and my team will take care of it.

I haven't done any performance comparisons to other i18n solutions available out there. The package is implementing the same behaviours as the original JS implementation plus a few more features and abstractions. We had no performance issues so far using it. we're also using the library to generate thousands of emails, translating different placeholder values in them. Haven't noticed any issues or huge performance impacts. Some of the functionality was optimized for the .Net world while we've ported the features over from JS.

If you have any other questions please let us know!

Greetings
DLK

**Comment by BlischkeFlorian** [comment]
I think I could help out, we are using it for several months now in various production environments with many customers, always works like a charm. I didn't find a feature which is not implemented from i18next, which I would have missed so far.

**Comment by PeterKottas** [comment]
Thanks a lot gents, definitely nice to see there are a few people who actively use this and take care of the repo. In my experience dot net community is much quieter then let's say front end javascript folks. Maybe that can explain the lack of stars/downloads. It might be a good idea to promote this a little bit to get some hype rolling. It seems like quite a cool piece of engineering, shame more people are not using it. For me the main driving force is compatibility with fed tools like https://github.com/gilmarsquinelato/i18n-manager. It would be great to be able to cater for both fed and backend with one toolset in regards of i18n. Anyways, I'll keep you posted if we have any problems/suggestions. Cheers!
