### ISSUE TITLE
Lazy loading from API

### ISSUE THREAD

**Issue by darkmakukudo** [DarkLiKally/I18Next.Net#12]
Any sample on how to lazy load using API?
The same feature for react here:
https://linguinecode.com/post/lazy-loading-react-i18next-translations

And also, does this support .NET 4.5?

**Comment by DarkLiKally** [comment]
It already tries to lazy load files from disk when the namespace is requested if you use the file based providers. If you need loading the translations from a database or some other source you have to implement your own translation backend and you can also implement lazy loading for namespaces there.

The package is built on .NET Standard 2.0 which is not supported by .NET Framework 4.5 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

You can use the package starting with .NET Framework 4.6.1
