### ISSUE TITLE
CurrentCulture vs CurrentUICulture

### ISSUE THREAD

**Issue by ArtemZag** [DarkLiKally/I18Next.Net#14]
According to the documentation of CurrentCulture & CurrentUICulture
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?view=net-5.0
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentuiculture?view=net-5.0

the first one (CurrentCulture) defines the format of numbers and dates.
The second one (CurrentUICulture) defines which resource to load (which translation to apply).

I wonder if it's a bug that this library uses CurrentCulture to determine which JSON files to load. Logically it has to use CurrentUICulture.

This is the code I'm talking about:
https://github.com/DarkLiKally/I18Next.Net/blob/5846638f4302272fea3a9328d07eaa4380251c7f/src/I18Next.Net/Plugins/ThreadLanguageDetector.cs#L21

**Comment by DarkLiKally** [comment]
Will change it :) Thanks for the notice
