### ISSUE TITLE
Is the library still maintained? What are the plans for the future?

### ISSUE THREAD

**Issue by JuergenRB** [DarkLiKally/I18Next.Net#17]
@DarkLiKally Do you have any news on the planned update and new version for resolving this PR?

_Originally posted by @csmith1983 in https://github.com/DarkLiKally/I18Next.Net/issues/13#issuecomment-1096305696_

**Comment by DarkLiKally** [comment]
I just merged the open PRs and now updating the rest off the stuff - adding builds for .net6 and so on and then publishing new versions on nuget.
