### ISSUE TITLE
Feature Request: Implement Namespace fallback

### ISSUE THREAD

**Issue by pschaeflein** [DarkLiKally/I18Next.Net#19]
To provide parity with the Javascript implementation, this library should implement Namespace fallback.

https://www.i18next.com/principles/fallback#namespace-fallback

**Comment by DarkLiKally** [comment]
Hello, thanks for your feedback, I'm working on it.

**Comment by DarkLiKally** [comment]
The implementation should be done, it will be included in the next release and after some more testing.
