### ISSUE TITLE
Check whether the value is already an IDictionary<string, object>

### ISSUE THREAD

**Issue by Maxwellwr** [DarkLiKally/I18Next.Net#2]
In the ObjectToDictionary(object value) extension method , check whether the value is already an IDictionary<string, object>

**Comment by DarkLiKally** [comment]
Thanks for your report. I'll fix that for the next version!

**Comment by DarkLiKally** [comment]
Ah I've seen your pull request. Merged! Will create a new release soon with also some new features.
