### ISSUE TITLE
Does this already support saveMissing and updateMissing backend configuration?

### ISSUE THREAD

**Issue by PhotoAtomic** [DarkLiKally/I18Next.Net#5]
Hello i've tryed to look at the code and search for docs but it doesn't seems to me that this library already supports the i18next saveMissing, and  updateMissing, backend configurrations, which allows the browser to signal missing keys (and the server should create them in the json file so they will be ready to be translated.

I'm i missing something? if the feature is missing i can probably contribute to the project implementing it. just let me know if i've missed it or there is at least something already implemented so i can pick up from there.

Thanks.

**Comment by DarkLiKally** [comment]
Hello PhotoAtomic,

currently there's no support for those features in the library that's correct. 
It's very busy in my life right now, so maybe if you could help me with development that would be very nice!
Thanks for your response and I'm really sorry for the late response on your issue. Had too much things going on over the last months.

**Comment by DarkLiKally** [comment]
@PhotoAtomic The next release (scheduled later today) will include an event on the translator (MissingKey) which will get fired when the key could not be resolved from the backend for the main language. You then could capture that event and update your data source with the missing keys. 
The event args also include a property PossibleKeys with variations for context and counts when relevant arguments are included in the translation call.

**Comment by metoule** [comment]
Could you provide an example on how to setup the event handler when using ASP.NET Core? For now, I'm using the following code, but it requires to know how to create a translator, which is a bit complex and might change in future releases:

````c#
services
    .AddI18NextLocalization(i18n => i18n
        .Configure(o => o.DetectLanguageOnEachTranslation = true)
        .AddInterpolator<HtmlInterpolator>()
        .AddTranslator(c =>
        {
            var backend = c.GetRequiredService<ITranslationBackend>();
            var logger = c.GetRequiredService<ILogger>();
            var pluralResolver = c.GetRequiredService<IPluralResolver>();
            var interpolator = c.GetRequiredService<IInterpolator>();
            var postProcessors = c.GetRequiredService<IEnumerable<IPostProcessor>>();

            var instance = new DefaultTranslator(backend, logger, pluralResolver, interpolator);
            instance.MissingKey += (obj, evt) => {
                // TODO handle event
            };

            instance.PostProcessors.AddRange(postProcessors);
            return instance;
        })
    )
    .AddMvc()
    .AddI18NextViewLocalization()
    ;
````

**Comment by DarkLiKally** [comment]
Hello @metoule,

you're right, that seems a bit complicated, I'll put it on my list to add configuration methods to access translator and other plugins directly. Thanks for the report!

Maybe for now you can use the following workaround, adding the callback inside the Configure method of your Startup class. This should work without problems because by default the services are registered as Singletons.

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.ApplicationServices.GetService<ITranslator>().MissingKey += (sender, args) => 
    {
        Console.WriteLine("Missing key: " + args.Key);
    };
    // ...
}
```

**Comment by DarkLiKally** [comment]
@metoule 
I've added a new plugin type IMissingKeyHandler. You can create your own implementation of it and add it like any other plugin `.AddMissingKeyHandler<MyCustomMissingKeyHandler>()`. This way you also get dependency injection for your handler.

The new version is still not published on nuget. I have to do some more work on other parts of the library and maybe add a few more features today evening.

I'll play around myself a bit more with the missing key handlers and if they're stable I'll schedule a new version for today or tomorrow.

Also I'm working on a bit more documentation starting with xml doc comments and then I'll continue with some git wiki pages.
