### ISSUE TITLE
NullReferenceException when using ThreadLanguageDetector and Accept-Language header is not present

### ISSUE THREAD

**Issue by Shaddix** [DarkLiKally/I18Next.Net#7]
We receive the following exception:
```
System.ArgumentNullException: Value cannot be null.
  at I18Next.Net.I18NextNet.set_Language(String value)
  at I18Next.Net.Extensions.I18NextStringLocalizer.Translate(String name, Object[] arguments)
```
when Accept-Language header is not present in http request (e.g. from Mobile app, not web-browser).

Set up is:
```
services.AddI18NextLocalization(
                i18N => i18N
                    .AddLanguageDetector<ThreadLanguageDetector>()
);
```

**Comment by DarkLiKally** [comment]
I'll have a look, thanks for your request!

**Comment by Shaddix** [comment]
On a side-note: it's only reproducible if server's CurrentCulture is InvariantCulture.
The fix is quite easy, I'll send a pull-request in few hours

**Comment by DarkLiKally** [comment]
Thanks, I'm currently working on some more optimizations, I will schedule a new release later this day! Also merging in your pull request.

**Comment by DarkLiKally** [comment]
@Shaddix Release was pushed to nuget.
